title:       "Alex Johnstone"
description: "Fond of Tea"

author: 'Alex Johnstone'
github_username:  'alexjj'
email: 'alexjj@gmail.com'
twitter_username: 'thealexjj'

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "posts"
    value:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

include:
- _pages

collections:
  articles:
    output: true

permalink: /:year-:month-:day/

tag_page: '/tags/'

plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate

paginate: 10
paginate_path: "/page:num/"

timezone: Europe/London

exclude:
- README.md
- usage-notes.txt
- /old-posts
- CNAME
